In [30]:
from typing import Callable
import math

func = lambda x : math.cos(x) - math.sin(x)

def Bisection(a: float, b: float, func: Callable[[float], float], iterations: int = 1, tolerance: float = 10**-6) -> None:
    a_i = a
    b_i = b

    for _ in range(1, iterations):
        x_i = (a_i + b_i) / 2

        if func(x_i) == 0 or ((b_i - a_i) / 2) < tolerance: 
            break

        if func(a_i)*func(x_i) < 0: b_i = x_i

        if func(x_i)*func(b_i) < 0: a_i = x_i
    
    print((a_i + b_i) / 2)

Bisection(0, 1, func, 20)

0.7853975296020508


In [ ]:
from typing import Callable

#phi = lambda x : 

def Fixed_Point(intervall: float, b: float, phi: Callable[[float], float], iterations: int = 1, tolerance: float = 10**-6) -> None:
    x_i = 


    for _ in range(1, iterations):

        if func(x_i) == 0 or ((b_i - a_i) / 2) < tolerance: 
            break

        if func(a_i)*func(x_i) < 0: b_i = x_i

        if func(x_i)*func(b_i) < 0: a_i = x_i
    
    print((a_i + b_i) / 2)

Bisection(0, 1, func, 20)

In [ ]:
x_guesses = [0.9, -0.7, 1.2, 2, 1.3, -1]
answers = [5/2, 3/2, 1, 1, 3/2, 5/2]
matrix = [[3, -1, 0, 0, 0, 1/2],
          [-1, 3, -1, 0, 1/2, 0],
          [0, -1, 3, -1, 0, 0],
          [0, 0, -1, 3, -1, 0],
          [0, 1/2, 0, -1, 3, -1],
          [1/2, 0, 0, 0, -1, 3]]

def Jacobi(x_guesses: list, answers: list, matrix: list[list], iterations: int = 1) -> None:
    N = len(answers)
    x_est = x_guesses

    for _ in range(1, iterations):
        x_new = [0] * N
        
        for eq_ind in range(N):
            res = answers[eq_ind]

            for e_ind in range(N):
                if e_ind != eq_ind:
                    res -= matrix[eq_ind][e_ind]*x_est[e_ind]

            x_new[eq_ind] = res / matrix[eq_ind][eq_ind]
        x_est = x_new

        print(x_est)

Jacobi(x_guesses, answers, matrix, 50)

[0.7666666666666666, 0.9833333333333333, 0.7666666666666666, 1.1666666666666667, 0.9500000000000001, 1.1166666666666665]
[0.9750000000000001, 0.8527777777777777, 1.05, 0.9055555555555556, 1.097222222222222, 1.0222222222222224]
[0.9472222222222223, 0.9921296296296297, 0.9194444444444444, 1.049074074074074, 1.000462962962963, 1.036574074074074]
[0.9912808641975309, 0.9554783950617284, 1.0137345679012346, 0.9733024691358025, 1.0298611111111111, 1.0089506172839506]
[0.9836676954732511, 0.9966949588477368, 0.9762602880658436, 1.0145318930041152, 1.0015046296296297, 1.0114068930041151]
[0.9969971707818931, 0.9863918895747599, 1.0037422839506174, 0.992588305898491, 1.0091971021947872, 1.0032235939643348]
[0.9949266975308642, 0.998713634545039, 0.9929933984910836, 1.004313128715135, 1.0008719850251486, 1.003566172267947]
[0.9989768494703553, 0.9958280345031244, 1.0010089210867248, 0.9979551278387441, 1.0028408279035208, 1.001136212086572]
[0.9984199761532794, 0.9995217855351065, 0.997927720780

In [ ]:
x_guesses = [0.9 , -0.7, 1.2, 2, 1.3, -1]
answers = [5/2, 3/2, 1, 1, 3/2, 5/2]
matrix = [[3, -1, 0, 0, 0, 1/2],
          [-1, 3, -1, 0, 1/2, 0],
          [0, -1, 3, -1, 0, 0],
          [0, 0, -1, 3, -1, 0],
          [0, 1/2, 0, -1, 3, -1],
          [1/2, 0, 0, 0, -1, 3]]

def Gauss_Seidel(x_guesses: list, answers: list, matrix: list[list], iterations: int = 1) -> None:
    N = len(answers)
    x_est = x_guesses

    for _ in range(1, iterations):
        
        for eq_ind in range(N):
            res = answers[eq_ind]

            for e_ind in range(N):
                if e_ind != eq_ind:
                    res -= matrix[eq_ind][e_ind]*x_est[e_ind]

            x_est[eq_ind] = res / matrix[eq_ind][eq_ind]

        print(x_est)

Gauss_Seidel(x_guesses, answers, matrix, 50)


[0.7666666666666666, 0.938888888888889, 1.312962962962963, 1.204320987654321, 0.41162551440329215, 0.842764060356653]
[1.0058356195701876, 1.204328608443835, 1.1362165320327187, 0.8492806821453369, 0.8632934794266908, 0.953458556547199]
[1.0758664433900786, 1.093478745236484, 0.9809198091272737, 0.9480710961846549, 0.9515967600378706, 0.9712211794476104]
[1.0359560518375597, 1.0136924936486327, 0.9872545299444293, 0.9796170966607667, 0.9813306764280202, 0.9877842168364134]
[1.006600128410142, 1.0010631067135203, 0.9935600677914289, 0.9916302480731497, 0.992960970517601, 0.9965536354375101]
[1.000928762998255, 0.9993361151769612, 0.9969887877500371, 0.9966499194225461, 0.9978451657571918, 0.9991269280860214]
[0.9999242170446502, 0.9993301406386972, 0.9986600200204144, 0.9988350619258687, 0.9994323065641805, 0.9998233993472851]
[0.9998061469883516, 0.9995833379088919, 0.9994727999449201, 0.9996350355030335, 0.9998889219652908, 0.999995282823705]
[0.9998618988323464, 0.9997967459315403, 0

In [ ]:
def SOR()  -> None:

In [67]:
import numpy as np

def LeastSquares(answers: list[int], estimateTo: int, order: int = 1):
    l = len(answers)
    matrixSTR = ''
    for index in range(l):
        matrixSTR += '1'
        for o in range(1, order+1):
            matrixSTR += f' {index**o}'
        matrixSTR += '; '

    matrixSTR = matrixSTR.strip().rstrip(';')

    A = np.matrix(matrixSTR)
    AT = A.transpose()
    ATA = AT @ A
    print(ATA)
    
    b = np.array(answers)
    ATb = AT @ b
    print(ATb)

    coefficients = np.linalg.solve(ATA, ATb.transpose())

    print(coefficients)

    sum = 0
    for ord in range(order+1):
        sum += coefficients[ord]*estimateTo**ord

    print(sum)
    
LeastSquares([67052,68008,69809,72024,73400,72063,74669,74487,74065,76777], 26, 3)

[[    10     45    285   2025]
 [    45    285   2025  15333]
 [   285   2025  15333 120825]
 [  2025  15333 120825 978405]]
[[   722354   3330549  21268479 151845861]]
[[ 6.65456657e+04]
 [ 2.46204274e+03]
 [-3.18802448e+02]
 [ 1.82538850e+01]]
[[235878.60512826]]
