In [ ]:
from typing import Callable
import math

func = lambda x : math.cos(x) - math.sin(x)

def Bisection(a: float, b: float, func: Callable[[float], float], iterations: int = 1, tolerance: float = 10**-6) -> None:
    a_i = a
    b_i = b

    for _ in range(1, iterations):
        x_i = (a_i + b_i) / 2

        if func(x_i) == 0 or ((b_i - a_i) / 2) < tolerance: 
            break

        if func(a_i)*func(x_i) < 0: b_i = x_i

        if func(x_i)*func(b_i) < 0: a_i = x_i
    
    x_est = (a_i + b_i) / 2
    #print(x_est)
    return x_est

Bisection(0, 1, func, 20)

0.7853975296020508

In [ ]:
from typing import Callable

#phi = lambda x : 

def Fixed_Point(intervall: float, b: float, phi: Callable[[float], float], iterations: int = 1, tolerance: float = 10**-6) -> None:
    x_i = 


    for _ in range(1, iterations):

        if func(x_i) == 0 or ((b_i - a_i) / 2) < tolerance: 
            break

        if func(a_i)*func(x_i) < 0: b_i = x_i

        if func(x_i)*func(b_i) < 0: a_i = x_i
    
    print((a_i + b_i) / 2)

Bisection(0, 1, func, 20)

In [102]:
x_guesses = [0.9, -0.7, 1.2, 2, 1.3, -1]
answers = [5/2, 3/2, 1, 1, 3/2, 5/2]
matrix = [[3, -1, 0, 0, 0, 1/2],
          [-1, 3, -1, 0, 1/2, 0],
          [0, -1, 3, -1, 0, 0],
          [0, 0, -1, 3, -1, 0],
          [0, 1/2, 0, -1, 3, -1],
          [1/2, 0, 0, 0, -1, 3]]

def Jacobi(x_guesses: list, answers: list, matrix: list[list], iterations: int = 1) -> None:
    N = len(answers)
    x_est = x_guesses

    for _ in range(1, iterations):
        x_new = [0] * N
        
        for eq_ind in range(N):
            res = answers[eq_ind]

            for e_ind in range(N):
                if e_ind != eq_ind:
                    res -= matrix[eq_ind][e_ind]*x_est[e_ind]

            x_new[eq_ind] = res / matrix[eq_ind][eq_ind]
        x_est = x_new

        #print(x_est)
    return(x_est)

Jacobi(x_guesses, answers, matrix, 50)

[0.9999999999998326,
 0.999999999999862,
 0.9999999999999041,
 1.0000000000000684,
 1.0000000000001776,
 1.0000000000001261]

In [103]:
x_guesses = [0.9 , -0.7, 1.2, 2, 1.3, -1]
answers = [5/2, 3/2, 1, 1, 3/2, 5/2]
matrix = [[3, -1, 0, 0, 0, 1/2],
          [-1, 3, -1, 0, 1/2, 0],
          [0, -1, 3, -1, 0, 0],
          [0, 0, -1, 3, -1, 0],
          [0, 1/2, 0, -1, 3, -1],
          [1/2, 0, 0, 0, -1, 3]]

def Gauss_Seidel(x_guesses: list, answers: list, matrix: list[list], iterations: int = 1) -> None:
    N = len(answers)
    x_est = x_guesses

    for _ in range(1, iterations):
        
        for eq_ind in range(N):
            res = answers[eq_ind]

            for e_ind in range(N):
                if e_ind != eq_ind:
                    res -= matrix[eq_ind][e_ind]*x_est[e_ind]

            x_est[eq_ind] = res / matrix[eq_ind][eq_ind]

        #print(x_est)
    return x_est

Gauss_Seidel(x_guesses, answers, matrix, 50)


[1.0, 1.0, 1.0, 1.0, 1.0, 1.0]

In [ ]:
def SOR()  -> None:

In [192]:
import numpy as np

def LeastSquares(answers: list[int], estimateTo: int, order: int = 1):
    l = len(answers)
    matrix = []
    for index in range(l):
        row = [1]
        for o in range(1, order+1):
            row.append(index**o)
        matrix.append(row)

    A = np.array(matrix)
    AT = A.transpose()
    ATA = AT @ A
    print(ATA)
    
    b = np.array(answers)
    ATb = AT @ b
    print(ATb)

    coefficients = np.linalg.solve(ATA, ATb.transpose())

    print(coefficients)

    sum = 0
    for ord in range(order+1):
        sum += coefficients[ord]*estimateTo**ord

    return sum
    
LeastSquares([67052,68008,69803,72024,73400,72063,74669,74487,74065,76777], 26, 3)

[[    10     45    285   2025]
 [    45    285   2025  15333]
 [   285   2025  15333 120825]
 [  2025  15333 120825 978405]]
[   722348   3330537  21268455 151845813]
[ 6.65455483e+04  2.46013947e+03 -3.18229021e+02  1.82130925e+01]


np.float64(235499.669463964)

In [188]:
import numpy as np
import math

def normOf(colum):
    norm = 0
    for e in colum:
        norm += e**2
    
    return math.sqrt(norm)

def GramSchmidt(matrix: list[list[int]], reduce: bool = False):
    Q = []
    R = []
    A = np.array(matrix)

    dim = A.shape
    colDepth = dim[0]
    rowDepth = dim[1]

    y_i = None
    q_i = np.array([0]*colDepth)

    for col in range(rowDepth):
        v_i = A[:, col]
        sum = 0
        for q in range(col):
            sum += Q[q] * (Q[q] @ v_i)
        y_i = v_i - sum
        norm_i = normOf(y_i)
        q_i = y_i / norm_i
        
        Q.append(q_i)
        row = []
        for c in range(col):
            row.append(0)
        row.append(norm_i)
        for c in range(col+1, rowDepth):
            row.append(q_i @ A[:, c])
        R.append(row)
    
    if not reduce:
        for _ in range(colDepth-rowDepth):
            R.append([0]*rowDepth)
        for _ in range(colDepth-rowDepth):
            pass
        

    Q = np.array(Q).transpose()
    R = np.array(R)

    #print(Q)
    #print()
    #print(R)

    return (Q, R)

GramSchmidt([[4,2,3,0], [-2,3,-1,1], [1,3,-4,2], [1,0,1,-1], [3,1,3,-2]])

(array([[ 0.71842121,  0.21150374,  0.2258696 ,  0.6085938 ],
        [-0.3592106 ,  0.7684636 ,  0.52281184, -0.05163138],
        [ 0.1796053 ,  0.59926061, -0.76877528, -0.13204504],
        [ 0.1796053 , -0.056401  ,  0.05246724, -0.40711782],
        [ 0.53881591,  0.04935087,  0.28615111, -0.66615837]]),
 array([[ 5.56776436,  1.43684242,  3.59210604, -1.25723711],
        [ 0.        ,  4.57553099, -2.43934318,  1.92468407],
        [ 0.        ,  0.        ,  4.14081864, -1.63950817],
        [ 0.        ,  0.        ,  0.        ,  1.42371311],
        [ 0.        ,  0.        ,  0.        ,  0.        ]]))

In [187]:
def matrix(input: list[int], order: int):
    matrix = []
    N = len(input)
    for index in range(N):
        row = []
        for o in range(order+1):
            row.append(input[index]**o)
        matrix.append(row)

    A = np.array(matrix)
    return A

x_i = np.linspace(1, 5, num=12)
y_i = []
A = matrix(x_i, 5)

for ord in range(len(x_i)):        
    y_i.append(sum(A[ord]))

Q_R = GramSchmidt(A, True)
R_hut = Q_R[1]
d_hut = Q_R[0].transpose() @ y_i

print(np.linalg.cond(R_hut, p=2))

322081.19636040035
